name: Rollback Database Migration

on:
  workflow_dispatch:
    inputs:
      migration_name:
        description: 'Migration to rollback to (e.g., 20250617011053_add_phone_and_name_columns)'
        required: true
        type: string
      confirm:
        description: 'Type "CONFIRM" to proceed with rollback'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verify confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "CONFIRM" ]; then
          echo "Rollback not confirmed. Exiting."
          exit 1
        fi
    
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Rollback migration
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
      run: |
        echo "Rolling back to migration: ${{ github.event.inputs.migration_name }}"
        npx prisma migrate resolve --rolled-back ${{ github.event.inputs.migration_name }}
        
    - name: Generate Prisma client
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
      run: npx prisma generate